name: test-gh
"on":
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: "1.17.6"
    - name: Check out code
      uses: actions/checkout@v3.0.1
    - name: Run Tests
      run: |
        set -e -x
        ./hack/test.sh
